version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: microservice
    image: in-gram:v0.0.1
    ports:
      - '3003:3003'
    env_file:
    - path: .docker.env
      required: true
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /src
          ignore:
            - node_modules/
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:
  pgadmin-data:

networks:
  backend:
    driver: bridge
